### ISSUE TITLE
macOS Catalina attempts to delete the executable

### ISSUE THREAD

**Issue by schrodincat** [deanishe/alfred-sublime-text#20]
<img width="532" alt="Screenshot 2019-10-08 at 03 50 01" src="https://user-images.githubusercontent.com/13354491/66359192-d4fcd000-e97e-11e9-8ec2-e0e91012324d.png">

macOS tries to delete the executable, if you click `Cancel` and then `Allow Anyway` inside System Preferences after that, it deletes the executable silently on the next try (oh, Apple).

Mirror issue for Alfred SSH workflow: https://github.com/deanishe/alfred-ssh/issues/25

**Comment by deanishe** [comment]
> it deletes the executable silently on the next try (oh, Apple)

So it's a bug in Catalina?

**Comment by schrodincat** [comment]
>> it deletes the executable silently on the next try (oh, Apple) ...

@deanishe perhaps, I’m not sure. The interesting thing here it’s only affects mentioned Go-based workflows. Is there something particular in the way those two invoke executables?

**Comment by deanishe** [comment]
> Is there something particular in the way those two invoke executables?

Most workflows tend to be scripts and don't contain binaries. AFAIK, there are similar issues with binary libraries, too.

The same restrictions don't apply to scripts. AFAIK, the only reason for that is because you can't reliably sign scripts: they're no safer to run than binaries.

Anyway, thanks for the heads-up. There doesn't appear to be anything I can do about it, unfortunately.

You could try building the workflow(s) yourself, or use the old Python version of this one, and try [isometry's SSH workflow](https://github.com/isometry/alfred-ssh).

**Comment by jefftriplett** [comment]
This blew up on me too. The fix for me was: 

1. System Preferences >> Security & Privacy >> General
1. Click the :lock: to allow changes
1. Then check out the Allow apps downloaded from: [x] App Store and identified developers
1. Restart Alfred
1. Try the workflow again
1. Back out of Security & Privacy
1. Re-enter Security & Privacy
1. There should now be an Allow alfsubl option which you'll want to allow
1. Restart Alfred again
1. Try the workflow again and repeat the steps #6+ as needed.

**Comment by schrodincat** [comment]
@jefftriplett thanks! It did work for me, the important part seems to be is to restart Alfred after clicking "Allow Anyway"

**Comment by vitorgalvao** [comment]
Have you tried locating the binary in question, right-clicking it and choosing `Open`? That’s the way you do it for apps, so it might work here as well.

**Comment by baa76** [comment]
(Also posted on Alfred Forum)

Hi there,
 
I was getting the same errors which were quite frustrating. Adding Alfred here has seemed to work for me.


![](https://content.invisioncic.com/r229491/monthly_2019_11/image.png.43eaeabac22a67dabb48d96e419a941a.png)

**Comment by schrodincat** [comment]
@baa76 do you know how to make this category appear in Settings?

**Comment by baa76** [comment]
At a guess you may need to install apple developer tools?
I had trouble with git after updating to Catalina and found [this stackoverflow thread](https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa) on updating the developer tools - this may do the trick although not certain? Perhaps somebody else more qualified may be able to verify.

**Comment by deanishe** [comment]
> At a guess you may need to install apple developer tools?

Ah, shit. That's a shame. I presume that setting will fix all workflows in one go.

**Comment by schrodincat** [comment]
That’s a problem, I have both dev tools and Xcode installed, and this section just disappeared...

**Comment by baa76** [comment]
[This article - specifically the section on Privacy](https://www.sentinelone.com/blog/macos-catalina-big-upgrad-dont-get-caught-out/) states that is a feature of Catalina - so perhaps nothing to do with Dev Tools? I am currently at the most recent version 10.15.1 - I will admit I didn't notice this preference until yesterday after upgrading the day before. But yes, it seems to have been the solution for all of these workflows.

**Comment by slyfogh** [comment]
> @jefftriplett thanks! It did work for me, the important part seems to be to restart Alfred after clicking `Allow Anyway`

It does not work for me. After clicking Allow away and restarting Alfred (via quit) right away, it brings the security warning again. Over and over again.

**Comment by stacksjb** [comment]
Right clicking works. Follow the following steps:
1) Right click on the "GIPHY" workflow in aired preferences, and click "Open in Finder"
2) Right click on the "giphy-alfredworkflow" app, then click Open (NOTE: regular double clicking will NOT work)
3) Click "Open"

The workflow will now work as expected. You may need to repeat these steps if you upgrade or reinstall the workflow later.

**Comment by joelmellon** [comment]
> Right clicking works.

This.

It's a common workaround that I'm sure every Mac power user has done plenty of times. The only trick here is locating the file. Since it's an Alfred workflow, it should be pretty obvious to start looking there.
