### ISSUE TITLE
STConfig workflow change

### ISSUE THREAD

**Issue by TheSecEng** [deanishe/alfred-sublime-text#38]
As I use this everyday, I sometimes run the stconfig rescan command. However it resets to `stconfig` once do. I think in this change if I ran rescan, it would default back to `st` so I could immediately search for my projects

**Comment by deanishe** [comment]
Alfred is in charge of sorting its own results. The workflow has no influence over that.

You can change the keyword for one or both actions.

**Comment by TheSecEng** [comment]
Sorry I wasn't clearer, I think the default behavior after rescanning should be calling `self.projects` not `self.config` If wee rescan, we likely want to drop back into projects to see our project and see if it was picked up by the rescan.

**Comment by deanishe** [comment]
Right, got you.

A couple of weeks ago, I’d have said “no” because  it wouldn’t be obvious where you’d ended up, but Alfred 4.1 added a new External Trigger mode that also shows the keyword.

I’ll have to check how I’ve structured the workflow. If it’s not a huge hassle, I’ll add this to the next release.
